version: "3.7"

networks:
  dapperzen:
    driver: bridge

services:
  postgres:
    hostname: postgres
    image: kartoza/postgis
    container_name: postgres
    networks:
      - dapperzen
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DBNAME: dapperzen, dapperzentest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - SERVICES=s3,eventbridge,

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
