version: '3.8'
services:
  migrations:
    image: flyway/flyway:9.22
    env_file:
      - ../dapz-auth-py-fastapi/envs/.env.development # TODO: this should be configurable, since we want to use the same flyway for all services
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/dapperzen
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_SCHEMAS=authservice
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_TABLE=schema_version
    depends_on:
      - postgres
    networks:
      - dapperzen
    volumes:
      - ../dapz-auth-py-fastapi/migrations:/flyway/sql
    command: ["migrate"]

  authservice: &authservice
    build:
      context: ../dapz-auth-py-fastapi
      dockerfile: Dockerfile.dev
    env_file:
      - ../dapz-auth-py-fastapi/envs/.env.development
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_RUN_HOST=''
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - dapperzen
    volumes:
      - ../dapz-auth-py-fastapi:/app
    entrypoint: ["uvicorn"]
    command: ["main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  authservice-debug:
    <<: *authservice
    ports:
      - "8000:8000"
      - "5678:5678"
    entrypoint: ["python"]
    command: ["-m", "debugpy", "--listen", "5678",
    "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  authservice-test:
    <<: *authservice
    ports:
      - "5678:5678"
    command: ["pytest", "-v", "--cov"]

  accessguard: &accessguard
    build:
      context: ../dapz-access-guard-py
      dockerfile: Dockerfile.dev
    env_file:
      - ../dapz-access-guard-py/envs/.env.development
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - dapperzen
    volumes:
      - ../dapz-access-guard-py:/app
    command: ["python", "setup.py", "bdist_wheel"]

  accessguard-test:
    <<: *accessguard
    env_file:
      - ../dapz-access-guard-py/envs/.env.testing
    ports:
      - "5678:5678"
    entrypoint: ["python" ,"-m"]
    command: ["pytest", "-vv", "--cov=.", "--cov-report=term-missing"]